### ISSUE TITLE
object 'res' not found

### ISSUE THREAD

**Issue by anniewest** [jchen1981/ZicoSeq#1]
Hi there, I'm trying to run ZicoSeq on my 16S rRNA data processed with the DADA2 pipeline, but every time it tries to fit the beta mixture I get the following error message:

`Fitting beta mixture ...
Error in rbeta(sample.no * post.sample.no, shape1 = x + res$shape1.1,  : 
  object 'res' not found`

I've tried playing around with my input table and metadata, changed the filter parameters etc. but nothing seems to be working. The function does work on the example throat data. The dimensions of my unfiltered ASV table compared to the example data are as follows:

My unfiltered ASV table:
```
int [1:6016, 1:133] 57254 1903 119 11683 39 14 0 0 0 43 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:6016] "TGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTTGTAAAGTACTTTCAGCGGGGAGGAAGGGAGTAAAGTTAATA"| __truncated__ "TGGGGAATATTGCACAATGGGGGGAACCCTGATGCAGCAACGCCGCGTGAAGGAAGAAGTATTTCGGTATGTAAACTTCTATCGATAGGGAAGAAAAAAATGACGGTACCT"| __truncated__ "TGGGGAATATTGCACAATGGGGGGAACCCTGATGCAGCAACGCCGCGTGAAGGAAGAAGTATTTCGGTATGTAAACTTCTATCAGCAGGGAAGAAAAAAATGACGGTACCT"| __truncated__ "TGGGGAATATTGCACAATGGGGGGAACCCTGATGCAGCAACGCCGCGTGAAGGAAGAAGTATTTCGGTATGTAAACTTCTATCGATAGGGAAGAAACAAATGACGGTACCT"| __truncated__ ...
  ..$ : chr [1:133] "ADELAIDE" "Alice" "Aparima" "Arab1" ...
```

Example OTU table:
```
int [1:856, 1:60] 1 0 0 0 0 0 0 0 0 0 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:856] "4695" "2983" "2554" "3315" ...
  ..$ : chr [1:60] "ESC_1.1_OPL" "ESC_1.3_OPL" "ESC_1.4_OPL" "ESC_1.5_OPL" ...
```

Any help would be greatly appreciated!

**Comment by jchen1981** [comment]
Are you using the ZicoSeq version in GUniFrac package? The github version is outdated.BestSent from my iPhoneOn Apr 5, 2023, at 5:40 PM, Annie ***@***.***> wrote:﻿
Hi there, I'm trying to run ZicoSeq on my 16S rRNA data processed with the DADA2 pipeline, but every time it tries to fit the beta mixture I get the following error message:
Fitting beta mixture ... Error in rbeta(sample.no * post.sample.no, shape1 = x + res$shape1.1,  :  object 'res' not found
I've tried playing around with my input table and metadata, changed the filter parameters etc. but nothing seems to be working. The function does work on the example throat data. The dimensions of my unfiltered ASV table compared to the example data are as follows:
My unfiltered ASV table:
`int [1:6016, 1:133] 57254 1903 119 11683 39 14 0 0 0 43 ...

attr(*, "dimnames")=List of 2
..$ : chr [1:6016] "TGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTTGTAAAGTACTTTCAGCGGGGAGGAAGGGAGTAAAGTTAATA"| truncated "TGGGGAATATTGCACAATGGGGGGAACCCTGATGCAGCAACGCCGCGTGAAGGAAGAAGTATTTCGGTATGTAAACTTCTATCGATAGGGAAGAAAAAAATGACGGTACCT"| truncated "TGGGGAATATTGCACAATGGGGGGAACCCTGATGCAGCAACGCCGCGTGAAGGAAGAAGTATTTCGGTATGTAAACTTCTATCAGCAGGGAAGAAAAAAATGACGGTACCT"| truncated "TGGGGAATATTGCACAATGGGGGGAACCCTGATGCAGCAACGCCGCGTGAAGGAAGAAGTATTTCGGTATGTAAACTTCTATCGATAGGGAAGAAACAAATGACGGTACCT"| truncated ...
..$ : chr [1:133] "ADELAIDE" "Alice" "Aparima" "Arab1" ...`

Example OTU table:
`int [1:856, 1:60] 1 0 0 0 0 0 0 0 0 0 ...

attr(*, "dimnames")=List of 2
..$ : chr [1:856] "4695" "2983" "2554" "3315" ...
..$ : chr [1:60] "ESC_1.1_OPL" "ESC_1.3_OPL" "ESC_1.4_OPL" "ESC_1.5_OPL" ...`

Any help would be greatly appreciated!

**Comment by anniewest** [comment]
Hi AP Chen,
Yes I'm using the GUniFrac package v.1.6

**Comment by jchen1981** [comment]
Please update to v1.7JunSent from my iPhoneOn Apr 5, 2023, at 10:17 PM, Annie ***@***.***> wrote:﻿
Hi AP Chen,
Yes I'm using the GUniFrac package v.1.6

**Comment by anniewest** [comment]
Sorry about that, update worked perfectly!!
