### ISSUE TITLE
All positive R2 in two-category variable

### ISSUE THREAD

**Issue by jorondo1** [jchen1981/ZicoSeq#5]
Hi,
Testing out Zicoseq for the first time. I have a grp.name that's a two category variable. I'm testing it on multiple different datasets where I expect several differential associations to go both ways (negative or positive, as tested with various other DAA tools). Overall, I tested 648 taxa and for every single one of them, the R2 is positive. Am right in expecting negative and positive R2 or am I misinterpreting this? 

dataset glimpse :

```
physeq@sam_data %>% as('data.frame') %>% str
'data.frame':	34 obs. of  5 variables:
 $ Sample_Number: num  11 13 21 25 27 28 29 30 32 34 ...
 $ Group        : Factor w/ 2 levels "Positive","Negative": 2 2 2 2 1 2 2 1 2 2 ...
```
Zicoseq call:

```
 ZicoSeq(
    feature.dat = physeq %>% otu_table %>% as.matrix,
    meta.dat = physeq %>% sample_data %>% as("data.frame"),
    grp.name = Group,
    mean.abund.filter = 0.001,
    perm.no = 999,
    outlier.pct = 0.01
```

**Comment by jchen1981** [comment]
If it is a categorical variable, Zicoseq performs an ANOVA-type test and all the R2 are positive to accommodate potential mutiple categories. If you want to have directions, please convert the categorical variable into a numeric variableSent from my iPhoneOn Oct 15, 2024, at 11:20 AM, Jonathan Rondeau-Leclaire ***@***.***> wrote:﻿
Hi,
Testing out Zicoseq for the first time. I have a grp.name that's a two category variable. I'm testing it on multiple different datasets where I expect several differential associations to go both ways (negative or positive, as tested with various other DAA tools). Overall, I tested 648 taxa and for every single one of them, the R2 is positive. Am right in expecting negative and positive R2 or am I misinterpreting this?
dataset glimpse :
***@***.***_data %>% as('data.frame') %>% str
'data.frame':	34 obs. of  5 variables:
 $ Sample_Number: num  11 13 21 25 27 28 29 30 32 34 ...
 $ Group        : Factor w/ 2 levels "Positive","Negative": 2 2 2 2 1 2 2 1 2 2 ...

Zicoseq call:
 ZicoSeq(
    feature.dat = physeq %>% otu_table %>% as.matrix,
    meta.dat = physeq %>% sample_data %>% as("data.frame"),
    grp.name = Group,
    mean.abund.filter = 0.001,
    perm.no = 999,
    outlier.pct = 0.01

**Comment by jorondo1** [comment]
Thanks a lot for responding so quickly @jchen1981 !
In this case, does that mean I should use a binary variable, e.g. 0/1 would that make sense? I'm not sure how that translates into interpreting the R2, as the aim here would be to be able to tell in which group the identified taxon is differentially more (or less ) abundant.

**Comment by jchen1981** [comment]
Yes, in this case the sign indicates the direction compared to the reference group coded as 0. R2 can be considered to be a normalized effect size indicating the association strength.JunSent from my iPhoneOn Oct 15, 2024, at 12:57 PM, Jonathan Rondeau-Leclaire ***@***.***> wrote:﻿
Thanks a lot for responding so quickly @jchen1981 !
In this case, does that mean I should use a binary variable, e.g. 0/1 would that make sense? I'm not sure how that translates into interpreting the R2, as the aim here would be to be able to tell in which group the identified taxon is differentially more (or less ) abundant.

**Comment by jorondo1** [comment]
Thank you very much !

**Comment by jorondo1** [comment]
Sorry for reopening this, I should have tested it before closing. I tried your suggestion by converting my factor to a numeric 0/1 variable and again, 100% of my effect sizes are positive (not just the significative one – all of the 24 bacterial families I'm testing. 

I tried both as.numeric() and as.double() and the results are the same as as.factor() (they vary a bit in terms of value, but every R2 is positive). 

Do you have any suggestions?

**Comment by jorondo1** [comment]
Please forgive me. I was looking at the R2, but it's the $coef.list that I should be looking at. Sorry for this and thanks again for your help !
